// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FiapCloudGames.Application.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CadastroDeUsuariosFeature : object, global::Xunit.IClassFixture<CadastroDeUsuariosFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Cadastro de Usuários", "  Como um visitante do sistema\r\n  Eu quero me cadastrar\r\n  Para ter acesso à plat" +
                "aforma", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CadastrarUsuario.feature"
#line hidden
        
        public CadastroDeUsuariosFeature(CadastroDeUsuariosFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
await testRunner.GivenAsync("que o usuário está na página de cadastro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CadastrarUsuario.feature.ndjson", 11);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário com credenciais válidas")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário com credenciais válidas")]
        [global::Xunit.TraitAttribute("Category", "UsuarioCadastroSucesso")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioComCredenciaisValidas()
        {
            string[] tagsOfScenario = new string[] {
                    "UsuarioCadastroSucesso"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário com credenciais válidas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 12
 await testRunner.WhenAsync("o usuário submete o formulário com dados válidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
 await testRunner.ThenAsync("o sistema deve registrar o usuário com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
 await testRunner.AndAsync("deve gerar um token de acesso válido", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário com credências inválidas - nome não preenchido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário com credências inválidas - nome não preenchido")]
        [global::Xunit.TraitAttribute("Category", "UsuarioCadastroInvalidoNomeNaoPreenchido")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioComCredenciasInvalidas_NomeNaoPreenchido()
        {
            string[] tagsOfScenario = new string[] {
                    "UsuarioCadastroInvalidoNomeNaoPreenchido"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário com credências inválidas - nome não preenchido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 18
  await testRunner.WhenAsync("o usuário submete o formulário com dados válidos de email e senha, porém não pree" +
                        "nche o nome", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
  await testRunner.ThenAsync("o sistema não registra o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
  await testRunner.AndAsync("retorna a mensagem de erro sobre o nome obrigatório ao usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário com credências inválidas - nome tamanho inválido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário com credências inválidas - nome tamanho inválido")]
        [global::Xunit.TraitAttribute("Category", "UsuarioCadastroInvalidoNomeTamanhoInvalido")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioComCredenciasInvalidas_NomeTamanhoInvalido()
        {
            string[] tagsOfScenario = new string[] {
                    "UsuarioCadastroInvalidoNomeTamanhoInvalido"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário com credências inválidas - nome tamanho inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 25
await testRunner.WhenAsync("o usuário submete o formulário com dados válidos de email e senha, porém preenche" +
                        " um nome com tamanho de caracteres maior ou menor que o permitido", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
await testRunner.ThenAsync("o sistema não registra o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 27
await testRunner.AndAsync("retorna a mensagem de erro sobre o nome tamanho inválido ao usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário com credências inválidas - email não preenchido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário com credências inválidas - email não preenchido")]
        [global::Xunit.TraitAttribute("Category", "UsuarioCadastroInvalidoEmailNaoPreenchido")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioComCredenciasInvalidas_EmailNaoPreenchido()
        {
            string[] tagsOfScenario = new string[] {
                    "UsuarioCadastroInvalidoEmailNaoPreenchido"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário com credências inválidas - email não preenchido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 31
await testRunner.WhenAsync("o usuário submete o formulário com dados válidos de nome de usuário e senha, poré" +
                        "m não preenche o email", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
await testRunner.ThenAsync("o sistema não registra o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
await testRunner.AndAsync("retorna mensagem de erro sobre o email obrigatório ao usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário credências inválidas - email tamanho inválido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário credências inválidas - email tamanho inválido")]
        [global::Xunit.TraitAttribute("Category", "UsuarioCadastroInvalidoEmailTamanhoInvalido")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioCredenciasInvalidas_EmailTamanhoInvalido()
        {
            string[] tagsOfScenario = new string[] {
                    "UsuarioCadastroInvalidoEmailTamanhoInvalido"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário credências inválidas - email tamanho inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 37
await testRunner.WhenAsync("o usuário submete o formulário com dados válidos de nome de usuário e senha, poré" +
                        "m com o tamanho de caractere maior ou menor que o permitido", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
await testRunner.ThenAsync("o sistema não registra o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
await testRunner.AndAsync("retorna mensagem de erro sobre o email de tamanho inválido ao usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário credências inválidas - formato de email incorreto")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário credências inválidas - formato de email incorreto")]
        [global::Xunit.TraitAttribute("Category", "UsuarioCadastroFormatoEmailIncorreto")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioCredenciasInvalidas_FormatoDeEmailIncorreto()
        {
            string[] tagsOfScenario = new string[] {
                    "UsuarioCadastroFormatoEmailIncorreto"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário credências inválidas - formato de email incorreto", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 43
await testRunner.WhenAsync("o usuário submete o formulário com dados válidos de nome de usuário e senha, poré" +
                        "m o formato do email preenchido está incorreto", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
await testRunner.ThenAsync("o sistema não registra o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
await testRunner.AndAsync("retorna mensagem de erro sobre o email em formato inválido ao usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário credênciais inválidas - senha não preenchida")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário credênciais inválidas - senha não preenchida")]
        [global::Xunit.TraitAttribute("Category", "UsuarioCadastroSenhaNaoPreenchida")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioCredenciaisInvalidas_SenhaNaoPreenchida()
        {
            string[] tagsOfScenario = new string[] {
                    "UsuarioCadastroSenhaNaoPreenchida"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário credênciais inválidas - senha não preenchida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 49
await testRunner.WhenAsync("o usuário submete o formulário com dados válidos de nome de usuário e email, poré" +
                        "m a senha não é preenchida", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
await testRunner.ThenAsync("o sistema não registra o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
await testRunner.AndAsync("retorna a mensagem de erro sobre a senha não preenchida ao usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário credências inválidas - senha tamanho inválido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário credências inválidas - senha tamanho inválido")]
        [global::Xunit.TraitAttribute("Category", "UsuarioCadastroSenhaTamanhoInvalido")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioCredenciasInvalidas_SenhaTamanhoInvalido()
        {
            string[] tagsOfScenario = new string[] {
                    "UsuarioCadastroSenhaTamanhoInvalido"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário credências inválidas - senha tamanho inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 55
await testRunner.WhenAsync("o usuário submete o formulário com dados válidos de nome de usuário e email, poré" +
                        "m o tamanho de caracteres da senha está inválido", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
await testRunner.ThenAsync("o sistema não registra o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 57
await testRunner.AndAsync("retorna a mensagem de erro sobre tamanho de senha inválido ao usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário credências inválidas - senha fraca")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Cadastro de Usuários")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário credências inválidas - senha fraca")]
        [global::Xunit.TraitAttribute("Category", "UsuarioCadastroSenhaFraca")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioCredenciasInvalidas_SenhaFraca()
        {
            string[] tagsOfScenario = new string[] {
                    "UsuarioCadastroSenhaFraca"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário credências inválidas - senha fraca", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 61
await testRunner.WhenAsync("o usuário submete o formulário com dados válidos de nome de usuário e email, poré" +
                        "m preenche uma senha fraca", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
await testRunner.ThenAsync("o sistema não registra o usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 63
await testRunner.AndAsync("retorna a mensagem de erro sobre senha informada é fraca ao usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CadastroDeUsuariosFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CadastroDeUsuariosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
