// <auto-generated />
using System;
using FiapCloundGames.API.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiapCloundGames.API.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505020921_Primeira_Migration")]
    partial class Primeira_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Biblioteca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId", "JogoId")
                        .IsUnique();

                    b.ToTable("Bibliotecas", (string)null);
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jogos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd0d99fe-0196-414b-b103-5a371c5e804b"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 6
                        },
                        new
                        {
                            Id = new Guid("8138c73c-fc4c-42c9-a316-ff7874069510"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 2
                        },
                        new
                        {
                            Id = new Guid("4ee09524-2c09-4283-a633-6e8ddd0b8d15"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 1
                        },
                        new
                        {
                            Id = new Guid("0b01cdf5-5421-4dfa-a40a-1df159b24571"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 6
                        },
                        new
                        {
                            Id = new Guid("52a756f6-392c-47e8-ad07-4c1ee260ed2f"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 4
                        },
                        new
                        {
                            Id = new Guid("942b8596-a092-45eb-8302-f9eabc1637dc"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 11
                        },
                        new
                        {
                            Id = new Guid("137ac0a2-d703-4fd7-a4fd-67b1a7bd21c4"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 6
                        },
                        new
                        {
                            Id = new Guid("58564834-2f6e-4d98-b3b3-f3c2ce2da0b0"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 4
                        },
                        new
                        {
                            Id = new Guid("4362aab0-06e5-455f-a19e-d4f585bde400"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 3
                        },
                        new
                        {
                            Id = new Guid("fb1d25ba-9e7f-44be-a716-f03914ee8430"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 14
                        },
                        new
                        {
                            Id = new Guid("a79a3378-3fe4-4bba-94be-440b097694ac"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = 4
                        });
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotivoDesativacao")
                        .HasColumnType("int");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aea0b4f3-d220-4c8d-aba8-d868be7ca593"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Perfil = 1
                        });
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Biblioteca", b =>
                {
                    b.HasOne("FiapCloundGames.API.Domain.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FiapCloundGames.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Jogo", b =>
                {
                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "PrecoBase", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecoBase");

                            b1.HasKey("JogoId");

                            b1.ToTable("Jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");

                            b1.HasData(
                                new
                                {
                                    JogoId = new Guid("fd0d99fe-0196-414b-b103-5a371c5e804b"),
                                    Valor = 61.99m
                                },
                                new
                                {
                                    JogoId = new Guid("8138c73c-fc4c-42c9-a316-ff7874069510"),
                                    Valor = 45.99m
                                },
                                new
                                {
                                    JogoId = new Guid("4ee09524-2c09-4283-a633-6e8ddd0b8d15"),
                                    Valor = 249.90m
                                },
                                new
                                {
                                    JogoId = new Guid("0b01cdf5-5421-4dfa-a40a-1df159b24571"),
                                    Valor = 19.90m
                                },
                                new
                                {
                                    JogoId = new Guid("52a756f6-392c-47e8-ad07-4c1ee260ed2f"),
                                    Valor = 73.99m
                                },
                                new
                                {
                                    JogoId = new Guid("942b8596-a092-45eb-8302-f9eabc1637dc"),
                                    Valor = 199.99m
                                },
                                new
                                {
                                    JogoId = new Guid("137ac0a2-d703-4fd7-a4fd-67b1a7bd21c4"),
                                    Valor = 61.99m
                                },
                                new
                                {
                                    JogoId = new Guid("58564834-2f6e-4d98-b3b3-f3c2ce2da0b0"),
                                    Valor = 229.90m
                                },
                                new
                                {
                                    JogoId = new Guid("4362aab0-06e5-455f-a19e-d4f585bde400"),
                                    Valor = 125.00m
                                },
                                new
                                {
                                    JogoId = new Guid("fb1d25ba-9e7f-44be-a716-f03914ee8430"),
                                    Valor = 24.99m
                                },
                                new
                                {
                                    JogoId = new Guid("a79a3378-3fe4-4bba-94be-440b097694ac"),
                                    Valor = 129.99m
                                });
                        });

                    b.OwnsMany("FiapCloundGames.API.Domain.Entities.Promocao", "Promocoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Ativo")
                                .HasColumnType("bit");

                            b1.Property<DateTime>("DataAlteracao")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DataCadastro")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("JogoId");

                            b1.ToTable("PromocaoJogos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JogoId");

                            b1.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "ValorPromocao", b2 =>
                                {
                                    b2.Property<Guid>("PromocaoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Valor")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ValorPromocao");

                                    b2.HasKey("PromocaoId");

                                    b2.ToTable("PromocaoJogos");

                                    b2.WithOwner()
                                        .HasForeignKey("PromocaoId");
                                });

                            b1.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Periodo", "Periodo", b2 =>
                                {
                                    b2.Property<Guid>("PromocaoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("DataFim")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("DataFim");

                                    b2.Property<DateTime>("DataInicio")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("DataInicio");

                                    b2.HasKey("PromocaoId");

                                    b2.ToTable("PromocaoJogos");

                                    b2.WithOwner()
                                        .HasForeignKey("PromocaoId");
                                });

                            b1.Navigation("Periodo")
                                .IsRequired();

                            b1.Navigation("ValorPromocao")
                                .IsRequired();
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Descricao");

                            b1.HasKey("JogoId");

                            b1.ToTable("Jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");

                            b1.HasData(
                                new
                                {
                                    JogoId = new Guid("fd0d99fe-0196-414b-b103-5a371c5e804b"),
                                    Valor = "Viaje pela Europa como o rei da estrada, um caminhoneiro que entrega cargas importantes em distâncias impressionantes."
                                },
                                new
                                {
                                    JogoId = new Guid("8138c73c-fc4c-42c9-a316-ff7874069510"),
                                    Valor = "Um simulador de sobrevivência espacial onde você gerencia seus colonos e os ajuda a cavar, construir e manter uma base asteroide subterrânea."
                                },
                                new
                                {
                                    JogoId = new Guid("4ee09524-2c09-4283-a633-6e8ddd0b8d15"),
                                    Valor = "Um jogo de ação e aventura em mundo aberto ambientado em um continente de Pywel, focado em sobrevivência e mercenários."
                                },
                                new
                                {
                                    JogoId = new Guid("0b01cdf5-5421-4dfa-a40a-1df159b24571"),
                                    Valor = "Gerencie sua própria empresa de caminhões e domine as estradas norte-americanas neste clássico da simulação."
                                },
                                new
                                {
                                    JogoId = new Guid("52a756f6-392c-47e8-ad07-4c1ee260ed2f"),
                                    Valor = "Desafie o deus dos mortos enquanto você abre caminho para fora do Submundo neste dungeon crawler roguelike."
                                },
                                new
                                {
                                    JogoId = new Guid("942b8596-a092-45eb-8302-f9eabc1637dc"),
                                    Valor = "Red Dead Redemption 2 é uma história épica de honra e lealdade no alvorecer dos tempos modernos."
                                },
                                new
                                {
                                    JogoId = new Guid("137ac0a2-d703-4fd7-a4fd-67b1a7bd21c4"),
                                    Valor = "Experimente a lendária liberdade americana dirigindo caminhões icônicos através de paisagens deslumbrantes e marcos históricos dos Estados Unidos."
                                },
                                new
                                {
                                    JogoId = new Guid("58564834-2f6e-4d98-b3b3-f3c2ce2da0b0"),
                                    Valor = "Levante-se, Maculado, e seja guiado pela graça para portar o poder do Anel Príncipio e se tornar um Lorde Príncipio nas Terras Intermédias."
                                },
                                new
                                {
                                    JogoId = new Guid("4362aab0-06e5-455f-a19e-d4f585bde400"),
                                    Valor = "Construa, automatize e gerencie fábricas complexas em um planeta alienígena infinito para lançar um foguete ao espaço."
                                },
                                new
                                {
                                    JogoId = new Guid("fb1d25ba-9e7f-44be-a716-f03914ee8430"),
                                    Valor = "Você herdou a antiga fazenda do seu avô. Com ferramentas de segunda mão e algumas moedas, você parte para começar sua nova vida."
                                },
                                new
                                {
                                    JogoId = new Guid("a79a3378-3fe4-4bba-94be-440b097694ac"),
                                    Valor = "Torne-se um caçador de monstros profissional e embarque em uma aventura épica para encontrar a criança da profecia em um mundo aberto vasto."
                                });
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.NomeJogo", "Nome", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nome");

                            b1.HasKey("JogoId");

                            b1.ToTable("Jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");

                            b1.HasData(
                                new
                                {
                                    JogoId = new Guid("fd0d99fe-0196-414b-b103-5a371c5e804b"),
                                    Valor = "Euro Truck Simulator 2"
                                },
                                new
                                {
                                    JogoId = new Guid("8138c73c-fc4c-42c9-a316-ff7874069510"),
                                    Valor = "Oxygen Not Included"
                                },
                                new
                                {
                                    JogoId = new Guid("4ee09524-2c09-4283-a633-6e8ddd0b8d15"),
                                    Valor = "Crimson Desert"
                                },
                                new
                                {
                                    JogoId = new Guid("0b01cdf5-5421-4dfa-a40a-1df159b24571"),
                                    Valor = "18 Wheels of Steel: Haulin'"
                                },
                                new
                                {
                                    JogoId = new Guid("52a756f6-392c-47e8-ad07-4c1ee260ed2f"),
                                    Valor = "Hades"
                                },
                                new
                                {
                                    JogoId = new Guid("942b8596-a092-45eb-8302-f9eabc1637dc"),
                                    Valor = "Red Dead Redemption 2"
                                },
                                new
                                {
                                    JogoId = new Guid("137ac0a2-d703-4fd7-a4fd-67b1a7bd21c4"),
                                    Valor = "American Truck Simulator"
                                },
                                new
                                {
                                    JogoId = new Guid("58564834-2f6e-4d98-b3b3-f3c2ce2da0b0"),
                                    Valor = "Elden Ring"
                                },
                                new
                                {
                                    JogoId = new Guid("4362aab0-06e5-455f-a19e-d4f585bde400"),
                                    Valor = "Factorio"
                                },
                                new
                                {
                                    JogoId = new Guid("fb1d25ba-9e7f-44be-a716-f03914ee8430"),
                                    Valor = "Stardew Valley"
                                },
                                new
                                {
                                    JogoId = new Guid("a79a3378-3fe4-4bba-94be-440b097694ac"),
                                    Valor = "The Witcher 3: Wild Hunt"
                                });
                        });

                    b.Navigation("Descricao")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("PrecoBase")
                        .IsRequired();

                    b.Navigation("Promocoes");
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("FiapCloundGames.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "ValorTotal", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("PrecoTotal");

                            b1.HasKey("PedidoId");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.OwnsMany("FiapCloundGames.API.Domain.Entities.PedidoJogo", "Jogos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("JogoId");

                            b1.HasIndex("PedidoId");

                            b1.ToTable("PedidoJogos", (string)null);

                            b1.HasOne("FiapCloundGames.API.Domain.Entities.Jogo", "Jogo")
                                .WithMany()
                                .HasForeignKey("JogoId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");

                            b1.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "ValorUnitario", b2 =>
                                {
                                    b2.Property<Guid>("PedidoJogoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Valor")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ValorUnitario");

                                    b2.HasKey("PedidoJogoId");

                                    b2.ToTable("PedidoJogos");

                                    b2.WithOwner()
                                        .HasForeignKey("PedidoJogoId");
                                });

                            b1.Navigation("Jogo");

                            b1.Navigation("ValorUnitario")
                                .IsRequired();
                        });

                    b.Navigation("Jogos");

                    b.Navigation("Usuario");

                    b.Navigation("ValorTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Email", "EmailUsuario", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = new Guid("aea0b4f3-d220-4c8d-aba8-d868be7ca593"),
                                    Valor = "admin@fiapcloudgames.com.br"
                                });
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Nome", "NomeUsuario", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Nome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = new Guid("aea0b4f3-d220-4c8d-aba8-d868be7ca593"),
                                    Valor = "Administrador Sistema"
                                });
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Senha", "Senha", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("Senha");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = new Guid("aea0b4f3-d220-4c8d-aba8-d868be7ca593"),
                                    Hash = "$2a$11$Soy4TsNUDtuazT6CJulPleFnp82cF5BkICiOmF9sk19x0X6pMAic."
                                });
                        });

                    b.Navigation("EmailUsuario")
                        .IsRequired();

                    b.Navigation("NomeUsuario")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
