// <auto-generated />
using System;
using FiapCloundGames.API.Infrastructure.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiapCloundGames.API.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Biblioteca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId", "JogoId")
                        .IsUnique();

                    b.ToTable("Bibliotecas", (string)null);
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jogos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd0d99fe-0196-414b-b103-5a371c5e804b"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(5129),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(5126),
                            Genero = 6
                        },
                        new
                        {
                            Id = new Guid("8138c73c-fc4c-42c9-a316-ff7874069510"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6077),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6076),
                            Genero = 2
                        },
                        new
                        {
                            Id = new Guid("4ee09524-2c09-4283-a633-6e8ddd0b8d15"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6080),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6080),
                            Genero = 1
                        },
                        new
                        {
                            Id = new Guid("0b01cdf5-5421-4dfa-a40a-1df159b24571"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6082),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6082),
                            Genero = 6
                        },
                        new
                        {
                            Id = new Guid("52a756f6-392c-47e8-ad07-4c1ee260ed2f"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6085),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6084),
                            Genero = 4
                        },
                        new
                        {
                            Id = new Guid("942b8596-a092-45eb-8302-f9eabc1637dc"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6087),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6086),
                            Genero = 11
                        },
                        new
                        {
                            Id = new Guid("137ac0a2-d703-4fd7-a4fd-67b1a7bd21c4"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6089),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6088),
                            Genero = 6
                        },
                        new
                        {
                            Id = new Guid("58564834-2f6e-4d98-b3b3-f3c2ce2da0b0"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6091),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6091),
                            Genero = 4
                        },
                        new
                        {
                            Id = new Guid("4362aab0-06e5-455f-a19e-d4f585bde400"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6093),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6093),
                            Genero = 3
                        },
                        new
                        {
                            Id = new Guid("fb1d25ba-9e7f-44be-a716-f03914ee8430"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6096),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6095),
                            Genero = 14
                        },
                        new
                        {
                            Id = new Guid("a79a3378-3fe4-4bba-94be-440b097694ac"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6098),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 189, DateTimeKind.Utc).AddTicks(6098),
                            Genero = 4
                        });
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotivoDesativacao")
                        .HasColumnType("int");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aea0b4f3-d220-4c8d-aba8-d868be7ca593"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 511, DateTimeKind.Utc).AddTicks(1584),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 511, DateTimeKind.Utc).AddTicks(1580),
                            Perfil = 2
                        },
                        new
                        {
                            Id = new Guid("e99c8caf-7067-49b4-8eef-b0d7ed801033"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 673, DateTimeKind.Utc).AddTicks(9012),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 673, DateTimeKind.Utc).AddTicks(9008),
                            Perfil = 0
                        },
                        new
                        {
                            Id = new Guid("bc359373-699b-4152-b63c-4fbf5a509aad"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 20, 5, 14, 838, DateTimeKind.Utc).AddTicks(1344),
                            DataCadastro = new DateTime(2026, 5, 2, 20, 5, 14, 838, DateTimeKind.Utc).AddTicks(1341),
                            Perfil = 0
                        });
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Biblioteca", b =>
                {
                    b.HasOne("FiapCloundGames.API.Domain.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FiapCloundGames.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Jogo", b =>
                {
                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "PrecoBase", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecoBase");

                            b1.HasKey("JogoId");

                            b1.ToTable("Jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");
                        });

                    b.OwnsMany("FiapCloundGames.API.Domain.Entities.Promocao", "Promocoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Ativo")
                                .HasColumnType("bit");

                            b1.Property<DateTime>("DataAlteracao")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DataCadastro")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("JogoId");

                            b1.ToTable("PromocaoJogos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JogoId");

                            b1.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "ValorPromocao", b2 =>
                                {
                                    b2.Property<Guid>("PromocaoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Valor")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ValorPromocao");

                                    b2.HasKey("PromocaoId");

                                    b2.ToTable("PromocaoJogos");

                                    b2.WithOwner()
                                        .HasForeignKey("PromocaoId");
                                });

                            b1.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Periodo", "Periodo", b2 =>
                                {
                                    b2.Property<Guid>("PromocaoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("DataFim")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("DataFim");

                                    b2.Property<DateTime>("DataInicio")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("DataInicio");

                                    b2.HasKey("PromocaoId");

                                    b2.ToTable("PromocaoJogos");

                                    b2.WithOwner()
                                        .HasForeignKey("PromocaoId");
                                });

                            b1.Navigation("Periodo")
                                .IsRequired();

                            b1.Navigation("ValorPromocao")
                                .IsRequired();
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Descricao");

                            b1.HasKey("JogoId");

                            b1.ToTable("Jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.NomeJogo", "Nome", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nome");

                            b1.HasKey("JogoId");

                            b1.ToTable("Jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");
                        });

                    b.Navigation("Descricao")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("PrecoBase")
                        .IsRequired();

                    b.Navigation("Promocoes");
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("FiapCloundGames.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "ValorTotal", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("PrecoTotal");

                            b1.HasKey("PedidoId");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.OwnsMany("FiapCloundGames.API.Domain.Entities.PedidoJogo", "Jogos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("JogoId");

                            b1.HasIndex("PedidoId");

                            b1.ToTable("PedidoJogos", (string)null);

                            b1.HasOne("FiapCloundGames.API.Domain.Entities.Jogo", "Jogo")
                                .WithMany()
                                .HasForeignKey("JogoId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");

                            b1.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "ValorUnitario", b2 =>
                                {
                                    b2.Property<Guid>("PedidoJogoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Valor")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ValorUnitario");

                                    b2.HasKey("PedidoJogoId");

                                    b2.ToTable("PedidoJogos");

                                    b2.WithOwner()
                                        .HasForeignKey("PedidoJogoId");
                                });

                            b1.Navigation("Jogo");

                            b1.Navigation("ValorUnitario")
                                .IsRequired();
                        });

                    b.Navigation("Jogos");

                    b.Navigation("Usuario");

                    b.Navigation("ValorTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Email", "EmailUsuario", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Nome", "NomeUsuario", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Nome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Senha", "Senha", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("Senha");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("EmailUsuario")
                        .IsRequired();

                    b.Navigation("NomeUsuario")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
