// <auto-generated />
using System;
using FiapCloundGames.API.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiapCloundGames.API.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Biblioteca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId", "JogoId")
                        .IsUnique();

                    b.ToTable("Bibliotecas", (string)null);
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jogos", (string)null);
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotivoDesativacao")
                        .HasColumnType("int");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aea0b4f3-d220-4c8d-aba8-d868be7ca593"),
                            Ativo = true,
                            DataAlteracao = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Perfil = 1
                        });
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Biblioteca", b =>
                {
                    b.HasOne("FiapCloundGames.API.Domain.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FiapCloundGames.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Jogo", b =>
                {
                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "PrecoBase", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecoBase");

                            b1.HasKey("JogoId");

                            b1.ToTable("Jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");
                        });

                    b.OwnsMany("FiapCloundGames.API.Domain.Entities.Promocao", "Promocoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Ativo")
                                .HasColumnType("bit");

                            b1.Property<DateTime>("DataAlteracao")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DataCadastro")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("JogoId");

                            b1.ToTable("PromocaoJogos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JogoId");

                            b1.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "ValorPromocao", b2 =>
                                {
                                    b2.Property<Guid>("PromocaoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Valor")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ValorPromocao");

                                    b2.HasKey("PromocaoId");

                                    b2.ToTable("PromocaoJogos");

                                    b2.WithOwner()
                                        .HasForeignKey("PromocaoId");
                                });

                            b1.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Periodo", "Periodo", b2 =>
                                {
                                    b2.Property<Guid>("PromocaoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("DataFim")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("DataFim");

                                    b2.Property<DateTime>("DataInicio")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("DataInicio");

                                    b2.HasKey("PromocaoId");

                                    b2.ToTable("PromocaoJogos");

                                    b2.WithOwner()
                                        .HasForeignKey("PromocaoId");
                                });

                            b1.Navigation("Periodo")
                                .IsRequired();

                            b1.Navigation("ValorPromocao")
                                .IsRequired();
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Descricao", "Descricao", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Descricao");

                            b1.HasKey("JogoId");

                            b1.ToTable("Jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.NomeJogo", "Nome", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nome");

                            b1.HasKey("JogoId");

                            b1.ToTable("Jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");
                        });

                    b.Navigation("Descricao")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("PrecoBase")
                        .IsRequired();

                    b.Navigation("Promocoes");
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("FiapCloundGames.API.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "ValorTotal", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("PrecoTotal");

                            b1.HasKey("PedidoId");

                            b1.ToTable("Pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.OwnsMany("FiapCloundGames.API.Domain.Entities.PedidoJogo", "Jogos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("JogoId");

                            b1.HasIndex("PedidoId");

                            b1.ToTable("PedidoJogos", (string)null);

                            b1.HasOne("FiapCloundGames.API.Domain.Entities.Jogo", "Jogo")
                                .WithMany()
                                .HasForeignKey("JogoId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");

                            b1.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Preco", "ValorUnitario", b2 =>
                                {
                                    b2.Property<Guid>("PedidoJogoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Valor")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ValorUnitario");

                                    b2.HasKey("PedidoJogoId");

                                    b2.ToTable("PedidoJogos");

                                    b2.WithOwner()
                                        .HasForeignKey("PedidoJogoId");
                                });

                            b1.Navigation("Jogo");

                            b1.Navigation("ValorUnitario")
                                .IsRequired();
                        });

                    b.Navigation("Jogos");

                    b.Navigation("Usuario");

                    b.Navigation("ValorTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("FiapCloundGames.API.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Email", "EmailUsuario", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = new Guid("aea0b4f3-d220-4c8d-aba8-d868be7ca593"),
                                    Valor = "admin@fiapcloudgames.com.br"
                                });
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Nome", "NomeUsuario", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Nome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = new Guid("aea0b4f3-d220-4c8d-aba8-d868be7ca593"),
                                    Valor = "Administrador Sistema"
                                });
                        });

                    b.OwnsOne("FiapCloundGames.API.Domain.ValueObjects.Senha", "Senha", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("Senha");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = new Guid("aea0b4f3-d220-4c8d-aba8-d868be7ca593"),
                                    Hash = "$2a$11$Soy4TsNUDtuazT6CJulPleFnp82cF5BkICiOmF9sk19x0X6pMAic."
                                });
                        });

                    b.Navigation("EmailUsuario")
                        .IsRequired();

                    b.Navigation("NomeUsuario")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
